const DRIVE_PRESENTATION_FILE_ID = "19g9bAi6zt6AXDIFAcrZJvUZk8IHiULrYyyMS99tEQ_s";
const SPREADSHEET_RATE_CARD_ID = "1XAWicqLSSNRNDszaDE9lY3I5iMODZF8Et-F61VYsEI4";
const SLIDES_TEMPLATE_ID = "1-3HWdxLu5RqLZyYs4BVD40GbVTlSCZhyeo6hLUkUxas";


export { DRIVE_PRESENTATION_FILE_ID, SPREADSHEET_RATE_CARD_ID, SLIDES_TEMPLATE_ID };