const DRIVE_PRESENTATION_FILE_ID = "< ADD YOUR SLIDE TEMPLATE ID HERE >"
const SPREADSHEET_RATE_CARD_ID = "< ADD YOUR SPREADSHEET ID HERE >"
const SLIDES_TEMPLATE_ID = "< ADD YOUR SPREADSHEET ID HERE >"


export { DRIVE_PRESENTATION_FILE_ID, SPREADSHEET_RATE_CARD_ID, SLIDES_TEMPLATE_ID };